### ISSUE TITLE
Publish the new image to docker hub

### ISSUE THREAD

**Issue by AiroPi** [marcoambrosini/aio-stalwart#5]
I was following the instructions from https://github.com/nextcloud/all-in-one/tree/main/community-containers/stalwart
But when I execute `sudo docker exec -it nextcloud-aio-stalwart configure.sh`, I get this series of questions :

1. Which database would you like to use? (RocksDB selected)
2. Where would you like to store e-mails and other large binaries? (Local file system selected)
3. Where would you like to store the full-text index? (RocksDB selected)
4. Where would you like to store the anti-spam database? (RocksDS selected)
5. Do you already have a directory or database containing your user accounts? (No, I want Stalwart to store my user accounts in RocksDB selected)

And it fail with :
`Failed to read configuration file /opt/stalwart-mail/etc/jmap/store.toml: No such file or directory (os error 2)`

**Comment by AiroPi** [comment]
Seems related to https://github.com/stalwartlabs/mail-server/issues/210

**Comment by AiroPi** [comment]
It seems that the image is just not published on docker hub. Can you please run the action? I am unable to do anything...

**Comment by marcoambrosini** [comment]
Done @AiroPi
