### ISSUE TITLE
Update aio-stalwart to latest stalwart version (v0.6.0)

### ISSUE THREAD

**Issue by AshanCG** [marcoambrosini/aio-stalwart#7]
Hi team,

After enabling stalwart with caddy (both community containers), we ran the `sudo docker exec -it nextcloud-aio-stalwart configure.sh` per https://github.com/nextcloud/all-in-one/tree/main/community-containers/stalwart#notes instructions and after that we get following error;

`Stalwart container started`
`Invalid configuration file: Invalid throttle key "remote_ip" found in "session.throttle.0000.key.0000"`.

We have tested this with isolate installation using `stalwartlabs/mail-server:v0.5.3` and we observe the same issue.

 stalwartlabs/mail-server  have issued v0.6.0 (https://github.com/stalwartlabs/mail-server/releases/tag/v0.6.0) few days ago. We tested isolated `stalwartlabs/mail-server:v0.6.0` and it works perfectly for us.
 
 At the moment, aio-stalwart set   `FROM stalwartlabs/mail-server:v0.5.3` - https://github.com/marcoambrosini/aio-stalwart/blob/main/Dockerfile. We suggest, in order to fix the above issue, to update the aio-stalwart with the latest stalwart version (v0.6.0).

**Comment by marcoambrosini** [comment]
Updated to 0.7.0 https://github.com/marcoambrosini/aio-stalwart/pull/9
